<?php

$resources = array(
'adminlogs' 		=> array('type' => 'native', 'singular' => 'adminlog', 'plural' => 'adminlogs', 'displayName' => 'admin logs', 'defaultNameField' => 'admin_title', 'extends' => 'null', 'database' => 'default', 'table' => 'admin_logs', 'alias' => 'admlog', 'searchable' => false, 'exposed' => 'false', 'crudability' => 'CRUD'),
'groups' 			=> array('type' => 'native', 'singular' => 'group', 'plural' => 'groups', 'displayName' => 'groups', 'defaultNameField' => 'admin_title', 'extends' => 'null', 'database' => 'default', 'table' => 'groups', 'alias' => 'gp', 'searchable' => false, 'exposed' => 'false', 'crudability' => 'CRUD'),
'groupsauths' 		=> array('type' => 'relation', 'singular' => 'groupsauth', 'plural' => 'groupsauths', 'displayName' => 'groups auths', 'defaultNameField' => 'null', 'extends' => 'null', 'database' => 'default', 'table' => 'groups_auths', 'alias' => 'gpauth', 'searchable' => false, 'exposed' => 'false', 'crudability' => 'CRUD'),
'pushsubscriptions' => array('type' => 'native', 'singular' => 'pushsubscription', 'plural' => 'pushsubscriptions', 'displayName' => 'push subscriptions', 'defaultNameField' => 'device_id', 'extends' => 'null', 'database' => 'default', 'table' => 'push_subscriptions', 'alias' => 'psub', 'searchable' => false, 'exposed' => 'false', 'crudability' => 'CRUD'),
'resources' 		=> array('type' => 'native', 'singular' => 'resource', 'plural' => 'resources', 'displayName' => 'resources', 'defaultNameField' => 'name', 'extends' => 'null', 'database' => 'default', 'table' => 'resources', 'alias' => 'res', 'searchable' => false, 'exposed' => 'false', 'crudability' => 'CRUD'),
'sessions' 			=> array('type' => 'native', 'singular' => 'session', 'plural' => 'sessions', 'displayName' => 'sessions', 'defaultNameField' => 'name', 'extends' => 'null', 'database' => 'default', 'table' => 'sessions', 'alias' => 'sess', 'searchable' => false, 'exposed' => 'false', 'crudability' => 'CRUD'),
'tasks' 			=> array('type' => 'native', 'singular' => 'task', 'plural' => 'tasks', 'displayName' => 'tasks', 'defaultNameField' => 'admin_title', 'extends' => 'null', 'database' => 'default', 'table' => 'tasks', 'alias' => 'tsk', 'searchable' => false, 'exposed' => 'false', 'crudability' => 'CRUD'),
'users' 			=> array('type' => 'native', 'singular' => 'user', 'plural' => 'users', 'displayName' => 'users', 'defaultNameField' => 'email', 'extends' => 'null', 'database' => 'default', 'table' => 'users', 'alias' => 'u', 'searchable' => false, 'exposed' => 'false', 'crudability' => 'CRUD'),
'usersgroups' 		=> array('type' => 'relation', 'singular' => 'usersgroup', 'plural' => 'usersgroups', 'displayName' => 'user-groups', 'defaultNameField' => 'null', 'extends' => 'null', 'database' => 'default', 'table' => 'users_groups', 'alias' => 'ugp', 'searchable' => false, 'exposed' => 'false', 'crudability' => 'CRUD'),
);
?>