<?php 

// [type]: 				int, float, varchar, bool, timestamp, datetime, enum
// [length]: 			length of the field value [for int and varchar] (default: int=11, varchar=255)
// [subtype]: 			file, fixedValues, URIname, fakebool, fileMetaData
// [possibleValues]: 	list of the possible values
// [pk]: 				primary key
// [fk]: 				foreign key
// [unique]: 			TODO
// [index]: 			TODO
// [required]: 			TODO: finished and functional?
// [relResource]: 		related to table
// [relField]: 			field to join on
// [relGetFields]: 		fields to get
// [relGetAs]: 			name of the gotten fields
// [list]: 				is the column displayed in list view table. (empty = 0 = false)
// [required]: 			is the data required. (default = false)
// [editable]: 			is the data editable in the admin. (default = true)
// [computed]: 			for data that should be generated by a computer process (ex: insertion date, random key, ...). (default = false)
// [computedValue]: 	
// [eval]: 				apply the specified eval command, replacing ---self--- by the field value. ex: 'eval' => 'strtolower(trim(---self---))'),
// [displayedValue]:
// [forceUpload]:
// [storeOn]: 	 		amazon_S3, amazon_EC2, default = ftp
// [acl]: 	 			S3_ACL_PRIVATE, S3_ACL_PUBLIC, S3_ACL_OPEN, S3_ACL_AUTH_READ. default = S3_ACL_PRIVATE
// [useField]:  
// [comment]: 			short summary of what the data represents, for admin display only. (- 60 chars).
// [displayName]:  
// [destRoot]: 			never should be stored in db.
// [exposed]: 			default = true
// [placeholder]: 		TODO
// [listTruncate]: 		In admin, in list view, will the displayed value truncated (default) or not
// [pivotResource]: 	name of the resource used as the pivot. default = {current column}_{relResource}. (ie: groups)
// [pivotLeftField]:	name of the 1st column used in the pivot relation. default = singular(current resource})_id. (ie: user_id)
// [pivotRightField]:	name of the 2nd column used in the pivot relation.default = singular(current resource})_id. (ie: group_id)

$resourceGroups = array(
);

### DATAMODEL: RESOURCES ###
$resources = array(
'apiclients' 		=> array('singular' => 'apiclient', 'table' => 'api_clients', 'alias' => 'apicl', 'defaultNameField' => 'name'),
'apps' 				=> array('singular' => 'app', 'alias' => 'app', 'defaultNameField' => 'admin_title'),
'appsplatforms' 	=> array('singular' => 'appsplatform', 'table' => 'apps_platforms', 'alias' => 'appptf', 'defaultNameField' => 'id', 'displayName' => 'apps platforms'),
'clients' 			=> array('singular' => 'client', 'alias' => 'c', 'defaultNameField' => 'admin_title'),
'contents' 			=> array('singular' => 'content', 'table' => 'issue_contents', 'alias' => 'ic', 'defaultNameField' => 'admin_title'),
'entries' 			=> array('singular' => 'entry', 'alias' => 'e', 'defaultNameField' => 'admin_title'),
'issues' 			=> array('singular' => 'issue', 'alias' => 'i', 'defaultNameField' => 'number'),
'groups' 			=> array('singular' => 'group', 'alias' => 'gp', 'crudability' => 'CRUD', 'defaultNameField' => 'admin_title'),
'groupsauths' 		=> array('singular' => 'groupsauth', 'table' => 'groups_auths',  'alias' => 'gpauth', 'crudability' => 'CRUD', 'defaultNameField' => 'group_id'),
'keywords' 			=> array('singular' => 'keyword', 'alias' => 'k', 'defaultNameField' => 'label'),
'machines' 			=> array('singular' => 'machine', 'alias' => 'mach', 'crudability' => 'CRUD', 'defaultNameField' => 'reference'),
'medias' 			=> array('singular' => 'media', 'table' => 'medias', 'alias' => 'me', 'defaultNameField' => 'admin_title'),
'pointsofinterest' 	=> array('singular' => 'pointofinterest', 'table' => 'points_of_interest', 'alias' => 'poi', 'defaultNameField' => 'admin_title', 'displayName' => 'Points of Interest'),
'platforms' 		=> array('singular' => 'platform', 'alias' => 'ptf', 'defaultNameField' => 'admin_title'),
'products' 			=> array('singular' => 'product', 'alias' => 'p', 'defaultNameField' => 'admin_title'),
'pushregistrations' => array('singular' => 'pushregistration','table' => 'push_registrations', 'alias' => 'pshreg','defaultNameField' => 'device_id','displayName' => 'push registrations'),
'resources' 		=> array('singular' => 'resource', 'alias' => 'res', 'crudability' => 'CRUD', 'defaultNameField' => 'name'),
'sessions' 			=> array('singular' => 'session', 'alias' => 'sess', 'crudability' => 'R', 'defaultNameField' => 'id'),
'users' 			=> array('singular' => 'user', 'alias' => 'u', 'crudability' => 'CRUD', 'defaultNameField' => 'email'),	
'usersgroups' 		=> array('singular' => 'usersgroup', 'table' => 'users_groups', 'alias' => 'ugp', 'crudability' => 'CRUD', 'defaultNameField' => 'user_id'),		
);

### DATAMODEL: RESOURCES COLUMNS ###
$dataModel = array(
'apiclients' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'name' 					=> array('type' => 'varchar', 'length' => 32, 'list' => 1),
	'private_key' 			=> array('type' => 'varchar', 'length' => 16, 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => true),
),
'apps' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'title_FR' 				=> array('type' => 'varchar', 'length' => 64, 'list' => 1),
	'title_EN' 				=> array('type' => 'varchar', 'length' => 64),
	'admin_title'			=> array('type' => 'varchar', 'subtype' => 'slug', 'from' => 'title_FR', 'length' => 64, 'list' => 1, 'comment' => 'For admin/url purpose. No special chars'),
	'clients_id' 			=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'clients', 'relField' => 'id', 'relGetFields' => 'name', 'relGetAs' => 'client_name'),
	'platforms_id' 			=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'platforms', 'relField' => 'id', 'relGetFields' => 'name', 'relGetAs' => 'platforms_name'),
	'description_FR' 		=> array('type' => 'text'),
	'description_EN' 		=> array('type' => 'text'),
	'baseline_short_FR'		=> array('type' => 'varchar', 'length' => 80, 'list' => 1),
	'baseline_short_EN'		=> array('type' => 'varchar', 'length' => 80),
	'desc_short_FR'			=> array('type' => 'text'),
	'desc_short_EN'			=> array('type' => 'text'),
	'download_url' 			=> array('type' => 'varchar', 'subtype' => 'url', 'list' => 1),
	'main_orientation' 		=> array('type' => 'enum', 'possibleValues' => array('none', 'portrait', 'landscape', 'mixed'), 'list' => 1),
	'main_color' 			=> array('type' => 'varchar', 'subtype' => 'color', 'length' => 20, 'list' => 1),
	'is_available' 			=> array('type' => 'bool', 'default' => 0, 'list' => 1),
	'is_displayable' 		=> array('type' => 'bool', 'default' => 0, 'list' => 1),
	'release_date'			=> array('type' => 'timestamp', 'default' => 'now', 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
),
'appsplatforms' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'apps_id' 				=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'apps', 'relField' => 'id', 'relGetFields' => 'admin_title', 'relGetAs' => 'apps_name'),
	'platforms_id' 			=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'platforms', 'relField' => 'id', 'relGetFields' => 'name', 'relGetAs' => 'platforms_name'),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
),
'clients' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'admin_title' 			=> array('type' => 'varchar', 'length' => 32, 'list' => 1),
	'name' 					=> array('type' => 'varchar', 'length' => 64, 'list' => 1),
	'logo_url' 				=> array('type' => 'varchar', 'subtype' => 'url', 'list' => 1),
	'website_url' 			=> array('type' => 'varchar', 'subtype' => 'url', 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
),
'contents' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'issues_id' 			=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'issues', 'relField' => 'id', 'relGetFields' => 'number', 'relGetAs' => 'issue_number','displayName' => 'number'),
	'admin_title' 			=> array('type' => 'varchar', 'length' => 64, 'list' => 1),
	'type' 					=> array('type' => 'enum', 'list' => 1, 'possibleValues' => array('sommaire','image_sommaire_plus','carte','fiche_decouverte','fiche_decouverte_savoir_plus','chapo_fiche_decouverte','sujet_photo','infographie','infographie_plus','histoire_du_jour','image_du_jour','bd','meteo','numero_photo','ours')),
	'heading' 				=> array('type' => 'varchar', 'length' => 64,),
	'title' 				=> array('type' => 'varchar', 'list' => 1),
	'text' 					=> array('type' => 'text'),
	'main_color' 			=> array('type' => 'varchar', 'subtype' => 'color', 'comment' => 'example: #b73133 or rgb(183,49,51) or rgba(183,49,51,0.5)'),
	'more_about' 			=> array('type' => 'text'),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'list' => 1),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => true, 'list' => 1),
	'origine' 				=> array('type' => 'enum', 'default' => 'human', 'possibleValues' => array('lpq_xml','human')),
),
'entries' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'admin_title' 			=> array('type' => 'varchar', 'length' => 32, 'list' => 1),
	'type' 					=> array('type' => 'enum', 'default' => 'news', 'possibleValues' => array('news','comment','blogPost','tweet','rssItem'), 'list' => 1),
	'title_FR' 				=> array('type' => 'varchar', 'length' => 64, 'list' => 1),
	'link_url' 				=> array('type' => 'varchar', 'subtype' => 'url', 'list' => 1),
	'origine_url' 			=> array('type' => 'varchar', 'subtype' => 'url'),
	'author_name' 			=> array('type' => 'varchar'),
	'summary_FR' 			=> array('type' => 'varchar'),
	'summary_EN' 			=> array('type' => 'varchar'),
	'text_FR' 				=> array('type' => 'text'),
	'text_EN' 				=> array('type' => 'text'),
	'publication_date'		=> array('type' => 'timestamp', 'default' => 'now', 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
),
'issues' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'number' 				=> array('type' => 'int', 'length' => 6, 'list' => 1),
	'date' 					=> array('type' => 'timestamp', 'list' => 1),
	'is_free' 				=> array('type' => 'bool', 'default' => 0, 'list' => 1),
	'price_euros' 			=> array('type' => 'varchar', 'length' => 16, 'list' => 1),
	'pdf_url' 				=> array('type' => 'varchar', 'subtype' => 'url', 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'list' => 1),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => true, 'list' => 1),
),
'groups' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'list' => 1, 'editable' => 0),
	'name' 					=> array('type' => 'varchar', 'length' => 32, 'list' => 1),
	'admin_title' 			=> array('type' => 'varchar', 'subtype' => 'slug', 'from' => 'name', 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
),
'groupsauths' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'group_id' 				=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'groups', 'relField' => 'id', 'relGetFields' => 'name', 'relGetAs' => 'group_name'),
	'resource_id' 			=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'resources', 'relField' => 'id', 'relGetFields' => 'name', 'relGetAs' => 'resource_name'),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'list' => 1),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1, 'list' => 1),
),
'keywords' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'issues_id' 			=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'issues', 'relField' => 'id', 'relGetFields' => 'number', 'relGetAs' => 'issue_number','displayName' => 'number'),
	'label' 				=> array('type' => 'varchar', 'length' => 128, 'list' => 1),
	'label_strict' 			=> array('type' => 'varchar', 'length' => 128, 'list' => 1),
	'definition' 			=> array('type' => 'text', 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => true),
),
'machines' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'reference' 			=> array('type' => 'varchar', 'length' => 16, 'list' => 1),
	'reference_type' 		=> array('type' => 'varchar', 'length' => 16, 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
),
'medias' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'title'					=> array('type' => 'varchar', 'length' => 255, 'list' => 1),
	'admin_title'			=> array('type' => 'varchar', 'subtype' => 'slug', 'from' => 'title', 'length' => 64, 'list' => 1, 'comment' => 'For admin/url purpose. No special chars'),
	'type' 					=> array('type' => 'enum', 'default' => 'image', 'possibleValues' => array('image','video','audio')),
	'url' 					=> array('type' => 'varchar', 'subtype' => 'file', 'list' => 1, 'allowedTypes' => 'jpg,png,gif', 'destFolder' => '/public/media/images/',  /*'destName' => 'media_%resource[\'id\']%.%file_extension%'*/),
	'width' 				=> array('type' => 'int', 'length' => 6, 'list' => 1),
	'height' 				=> array('type' => 'int', 'length' => 6, 'list' => 1),
	'entries_id' 			=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'entries', 'relField' => 'id', 'relGetFields' => 'admin_title', 'relGetAs' => 'entry_title'),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
),
'platforms' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'name' 					=> array('type' => 'varchar', 'length' => 32, 'list' => 1),
	'admin_title'			=> array('type' => 'varchar', 'subtype' => 'slug', 'from' => 'name', 'length' => 64, 'list' => 1, 'comment' => 'For admin/url purpose. No special chars'),
	'constructor' 			=> array('type' => 'varchar', 'length' => 64, 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
	'position' 				=> array('type' => 'int', 'length' => 4, 'default' => 0, 'list' => 1, 'comment' => 'Used for display order. Higher is stronger.'),
),
'pointsofinterest' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'issues_id' 			=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'issues', 'relField' => 'id', 'relGetFields' => 'number', 'relGetAs' => 'issue_number','displayName' => 'number'),
	'contents_id' 			=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'contents', 'relField' => 'id', 'relGetFields' => 'admin_title', 'relGetAs' => 'point_title','displayName' => 'content'),
	'admin_title' 			=> array('type' => 'varchar', 'length' => 64, 'list' => 1),
	'title' 				=> array('type' => 'varchar', 'lenght' => 128, 'list' => 1),
	'text' 					=> array('type' => 'text', 'subtype' => 'html'),
	'coordinates' 			=> array('type' => 'varchar', 'length' => 20, 'list' => 1, 'comment' => '(in pixels). Order: origine X, origine Y, width, height. Values are separated by spaces or comas.', 'placeholder' => 'ex: 17,258,27,112'),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => true),
),
'products' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
		'admin_title' 			=> array('type' => 'varchar', 'length' => 32, 'list' => 1),
		'title_FR' 				=> array('type' => 'varchar', 'length' => 64, 'list' => 1),
		'title_EN' 				=> array('type' => 'varchar', 'length' => 64, 'list' => 1),
		'description_FR' 		=> array('type' => 'text'),
		'description_EN' 		=> array('type' => 'text'),
		'creation_date'			=> array('type' => 'timestamp', 'list' => 1, 'editable' => false,'computed' => true, 'computedValue' => 'NOW()'),
		'update_date'			=> array('type' => 'timestamp', 'list' => 1,'computed' => true, 'computedValue' => 'NOW()', 'forceUpdate' => true),
		'price_euros' 			=> array('type' => 'varchar', 'length' => 10, 'default' => '800', 'list' => 1),
		'price_dollars' 		=> array('type' => 'varchar', 'length' => 10, 'default' => '1000', 'list' => 1),
		'available_nb' 			=> array('type' => 'int', 'default' => 200, 'list' => 1),
),
'pushregistrations' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'token' 				=> array('type' => 'varchar', 'list' => 1),
	'device_id' 			=> array('type' => 'varchar', 'length' => 128, 'list' => 1,'displayName' => 'device id', 'unique' => 1),
	'language' 				=> array('type' => 'varchar', 'length' => 5, 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
),
'resources' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'list' => 1, 'editable' => 0),
	'name' 					=> array('type' => 'varchar', 'length' => 32, 'list' => 1),
	'singular' 				=> array('type' => 'varchar', 'length' => 32, 'list' => 1),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'list' => 1),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1, 'list' => 1),
),
'usersgroups' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'user_id' 				=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'users', 'relField' => 'id', 'relGetFields' => 'email', 'relGetAs' => 'user_email'),
	'group_id' 				=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'relResource' => 'groups', 'relField' => 'id', 'relGetFields' => 'name', 'relGetAs' => 'group_name'),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'list' => 1),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1, 'list' => 1),
),
'users' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'AI' => 1, 'list' => 1, 'editable' => 0),
	'email' 				=> array('type' => 'varchar', 'subtype' => 'email', 'list' => 1),
	'password' 				=> array('type' => 'varchar', 'subtype' => 'password', 'hash' => 'sha1', 'length' => 64, 'list' => 1),
	'first_name' 			=> array('type' => 'varchar', 'length' => 64, 'list' => 1, 'eval' => 'strtolower(trim(---self---))'),
	'last_name' 			=> array('type' => 'varchar', 'length' => 64, 'list' => 1, 'eval' => 'strtolower(trim(---self---))'),
	'auth_level' 			=> array('type' => 'enum', 'default' => 'user', 'possibleValues' => array('user','contributor','admin','superadmin','god'), 'editable' => 0),
	'auth_level_nb' 		=> array('type' => 'int', 'default' => 10, 'editable' => 0, 'comment' => '10=user, 100=contributor, 500=admin, 1000=superadmin, 10000=god'),
	//'groups' 				=> array('type' => 'onetomany', 'relResource' => 'groups', 'relField' => 'id', 'pivotResource' => 'users_groups', 'pivotLeftField' => 'user_id', 'pivotRightField' => 'group_id', 'getFields' => 'admin_title'),
	'groups' 				=> array('type' => 'onetomany', 'getFields' => 'id,admin_title'),
	'company' 				=> array('type' => 'varchar', 'length' => 64),
	'address' 				=> array('type' => 'varchar'),
	'zipcode' 				=> array('type' => 'varchar', 'length' => 16),
	'city' 					=> array('type' => 'varchar', 'length' => 32),
	'country' 				=> array('type' => 'varchar', 'length' => 64),
	'TCS_accepted' 			=> array('type' => 'bool', 'default' => 0, 'list' => 1, 'comment' => 'Terms and Condtions of Sales accepted?'),
	'TU_accepted' 			=> array('type' => 'bool', 'default' => 0, 'list' => 1, 'comment' => 'Terms of Use accepted?'),
	'billing_address' 		=> array('type' => 'varchar'),
	'billing_zipcode' 		=> array('type' => 'varchar', 'length' => 16),
	'billing_city' 			=> array('type' => 'varchar', 'length' => 32),
	'billing_country' 		=> array('type' => 'varchar', 'length' => 64),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
),
'sessions' => array(
	'id' 					=> array('type' => 'int', 'pk' => 1, 'list' => 1, 'editable' => 0),
	'name' 					=> array('type' => 'varchar', 'length' => 32, 'list' => 1, 'editable' => 0),
	'user_id' 				=> array('type' => 'int', 'fk' => 1, 'list' => 1, 'editable' => 0, 'relResource' => 'users', 'relField' => 'id', 'relGetFields' => 'email', 'relGetAs' => 'user_email','displayName' => 'user'),
	'creation_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now'),
	'update_date'			=> array('type' => 'timestamp', 'editable' => 0, 'default' => 'now', 'forceUpdate' => 1),
	'expiration_time'		=> array('type' => 'timestamp', 'list' => 1, 'editable' => 1),
	'ip' 					=> array('type' => 'varchar', 'length' => 48, 'list' => 1, 'editable' => 0),
	'last_url' 				=> array('type' => 'varchar', 'subtype' => 'url', 'list' => 1, 'editable' => 0, 'forceUpdate' => 1),
	),
);


?>