<?php

$errorsAssoc = array(

	'21' => array('back' => 'Resource columns not defined',
					'front' => _('Columns for the queried resource are not defined.')),
	'22' => array('back' => 'Resource(s) columns not defined',
					'front' => _('Columns for one or more of the queried resource(s) are not defined.')),

	// NO error should be defined with error between 100 & 1000 (assumed to be reserved to HTTP status codes)
	'1000' => array('back' => 'Missing required params',
					'front' => _('Missing required parameter(s).')),
	'1001' => array('back' => 'Missing required param %s',
					'front' => _('Missing required parameter: %s.')),
	'1002' => array('back' => 'Missing required fields: %s',
					'front' => _('Please fill all the required fields: %s')),
	'1003' => array('back' => 'Missing required field(s): %s',
					'front' => _('Please fill all the required fields: %s')),

	'1007' => array('back' => 'Invalid format for field: %s',
					'front' => _('The format of the following field is invalid: %s')),					
	'1008' => array('back' => 'Invalid format for field(s): %s',
					'front' => _('The format of the following field(s) are invalid: %s')),
					
	'1010' => array('back' => 'Wrong %s value',
					'front' => _('The passed %s value is not the expected one.')),
					
	'1051' => array('back' => 'Missing required % resource(s)',
					'front' => _('One or more resource(s) could not be found')),
					
	'4000' => array('back' => 'Database connection error',
					'front' => _('An error occured on the site\'s database. Please come back later.')),
	'4001' => array('back' => 'Database selection error',
					'front' => _('An error occured on the site\'s database. Please come back later.')),
	'4010' => array('back' => 'Database query error',
					'front' => _('An error occured on the site\'s database. Please come back later.')),
	'4020' => array('back' => 'Database query syntax error',
					'front' => _('There\'s a syntax error in a database request.')),
	'4030' => array('back' => 'Creation error due to unique key constraint',
					'front' => _('The resource(s) could not be created because there\'s already an unique record with passed data association(s).')),
	'4050' => array('back' => 'Creation/update error due to fk constraint(s)',
					'front' => _('The resource(s) could not be created/updated because one or more required field(s) are missing/empty.')),
	'4061' => array('back' => 'Column(s) cannot be null',
					'front' => _('The resource(s) could not be created because one or more field(s) have not been filled.')),
	'4080' => array('back' => '%s',
					'front' => _('Your query contains one or more unknown column(s)')),
	'4081' => array('back' => 'Unknown column: %s',
					'front' => _('Your query contains one or more unknown column(s): %s')),
	'4100' => array('back' => 'DB error message: %s',
					'front' => _('Returned database error message: %s')),
	'4110' => array('back' => 'Deletion error due to fk constraint(s)',
					'front' => _('The resource(s) could not be deleted because other resource(s) are pointing to it (them). Please update/delete sibling resources first.')),
	'4150' => array('back' => 'Tables alias conflict.',
					'front' => _('Some resources seems to use the same alias, creating a conflict.')),
					
	'4210' => array('back' => 'Wrong condition format: %s',
					'front' => _('Wrong condition format. Expected: column|[operator]|values. Received: %s')),
	'4212' => array('back' => 'Unknown condition resource/table: %s',
					'front' => _('Unknown condition resource/table: %s')),
	'4213' => array('back' => 'Unknown condition column: %s',
					'front' => _('Unknown condition field/column: %s')),
	'4215' => array('back' => 'Unknown condition operator: %s',
					'front' => _('Unknown condition operator: %s')),
	'4217' => array('back' => 'Invalid values for condition: %s',
					'front' => _('Expected: 2 values for the passed condition column/operator couple: %s/%s')),
	'4220' => array('back' => 'Invalid values for condition: %s',
					'front' => _('Expected: an unique value for the passed condition column/operator couple: %s/%s')),
					
	'5000' => array('back' => 'Common error.',
					'front' => _('An error occured during the process, please retry later')),
					
	'6050' => array('back' => 'Password update error.',
					'front' => _('You are not allowed to edit the password of this user.')),
	'6100' => array('back' => 'Unauthorised uploaded filetype.',
					'front' => _('The filetype of (one of) the uploaded file(s) is not an authorised filetype.')),
	'6110' => array('back' => 'File upload error.',
					'front' => _('An error occured during the file upload.')),
	
	'9000' => array('back' => 'Access unauthorized.',
					'front' => _('You don\'t have the permissions to access this page/section.')),
	'9100' => array('back' => 'Invalid CSRF Token.',
					'front' => _('We think you may not really wanted to do this. If we are wrong, please retry.')),

	// TODO: Do some cleaning by using more generic messages instead 
	'10000' => array('back' => 'Missing required fields',					// Deprecated: use 1002 instead
					'front' => _('Please fill all the required fields')), 	// Deprecated: use 1002 instead
	'10001' => array('back' => 'Invalid email',
					'front' => _('This email address is not valid')),
	'10002' => array('back' => 'Unknown email adress',
					'front' => _('Invalid email and/or password')),
	'10003' => array('back' => 'Password not correct',
					'front' => _('Invalid email and/or password')),
	'10004' => array('back' => 'Passwords not matching',
					'front' => _('The password and it\'s confirmation are not identical')),
	'10005' => array('back' => 'Account not confirmed',
					'front' => _('Your account has not already been confirmed.')),
	'10006' => array('back' => 'Incorrect login format',
					'front' => _('Login not correct. Only letters or numerics (3 to 32 characters) are allowed.')),
	'10007' => array('back' => 'Incorrect password format',
					'front' => _('Password not correct. Only letters and numbers are allowed.')),
	'10009' => array('back' => 'Incorrect captcha format',
					'front' => _('Anti-spam filter not correct. Only numerics are allowed.')),
	'10010' => array('back' => 'Incorrect captcha value',
					'front' => _('Anti-spam filter value not correct. Figure of 2 numerics expected.')),


	'10014' => array('back' => 'Incorrect old password format',
					'front' => _('Old password not correct. Only letters and numbers are allowed.')),
	'10015' => array('back' => 'Incorrect new password format',
					'front' => _('New password not correct. Only letters and numbers are allowed.')),
	'10016' => array('back' => 'Wrong current password',
					'front' => _('Your current password is not valid')),
	'10017' => array('back' => 'Missing reset password key in database',
					'front' => _('You are not allowed reset your password. Please use the \'lost password?\' feature first.')),
	'10018' => array('back' => 'Wrong security reset password key',
					'front' => _('The security key you are using is not the expected one. Return to the \'lost password?\' page to get a new mail with a new reset password link.')),
	'10019' => array('back' => 'Last 2 passwords and current one are not allowed.',
					'front' => _('You are not allowed to use neither one of your 2 previous passwords nor the current one. Please choose another one.')),
	'10020' => array('back' => 'Login already exists',
					'front' => _('Login already existing. Choose another one.')),
	'10021' => array('back' => 'Email already exists',
					'front' => _('Email already existing. Choose another one.')),
	'10022' => array('back' => 'Incorrect firstname format',
					'front' => _('Only letters and dashes are allowed (1 to 32 characters).')),
	'10023' => array('back' => 'Incorrect firstname format',
					'front' => _('Only letters and dashes are allowed (1 to 32 characters).')),
	'10024' => array('back' => 'Incorrect laststname format',
					'front' => _('Only letters and dashes are allowed.')),
	'10030' => array('back' => 'Too many login attemps',
					'front' => _('You have reached the max unsucessful login attemps number. For security issue, you won\'t be able to login during ' . _APP_MAX_LOGIN_ATTEMPTS_BAN_TIME . ' seconds.')),
	'10031' => array('back' => 'Failed login attemp',
					'front' => _('Remaining login attempts before this account is blocked: %s')),
	'10032' => array('back' => 'Account blocked',
					'front' => _('Your account has been blocked. Please contact us by email: %')),
	'10033' => array('back' => 'Password expired',
					'front' => _('Your password is expired. You have to change it to be able to login again.')),
	'10035' => array('back' => 'Last password change too recent',
					'front' => _('Your last password change is too recent. The minimun time between 2 password changes is: ') . _(_APP_PASS_MIN_TIME_BETWEEN_CHANGES_H)),
					
	'10100' => array('back' => 'Session expired',
					'front' => _('Your session has expired. Please login again.'),
					'buttons' => array(array(
						'label' => _('Re-connect'),
						'href' 	=> _URL_LOGIN,
						'id' 	=> 'errorReconnectBtn',
					))),
	'10101' => array('back' => 'Session corrupted',
				'front' => _('Your session has been corrupted. Please login again.')),
					
	'10205' => array('back' => 'Unknown email',
					'front' => _('Unknown email.')),
					
	'10310' => array('back' => 'Incorrect creditCardOwnerName format',
					'front' => _('Credit card owner name not correct. Only letters and spaces (3 to 64 characters).')),
	'10315' => array('back' => 'Incorrect creditCardCardNumber value',
					'front' => _('Credit card number value not correct. Figure of 16 numerics expected.')),
	'10320' => array('back' => 'Incorrect creditCardCryptogram value',
					'front' => _('Credit card cryptogram value not correct. Figure of 3 numerics expected.')),
					
	'12000' => array('back' => 'WS call exception',
					'front' => _('An error occured during the request. Please retry later.')),	
	
	'15010' => array('back' => 'Controller folder unwritable.',
					'front' => _('The file could not be created. The parent folder %s is not writable.')),
	'15011' => array('back' => 'Controller file unwritable.',
					'front' => _('The file %s is not writable.')),
					
	### APP SPECIFICS ###
	// TODO: use generic error code instead (1003?)
	'20010' => array('back' => 'Missing email',
					'front' => _('Please provide an email.')),
	'20012' => array('back' => 'Missing password',
					'front' => _('Please provide a password.')),
	'20013' => array('back' => 'Missing new password',
					'front' => _('Please provide a new password.')),
	'20014' => array('back' => 'Missing new password confirmation',
					'front' => _('Please provide a new password confirmation.')),
					

);
?>